export type FFmpegMode = 'simple' | 'professional';
export type AppLanguage = 'zh-TW' | 'en-US';

export interface AIAdvice {
  command: string;
  explanation: string;
  keyCategories: string[];
  suggestedState?: Partial<FFmpegState>;
}

export interface FFmpegState {
  // Application State
  language: AppLanguage;
  mode: FFmpegMode;

  // Input/Output
  inputFiles: string[];
  outputFile: string;
  format: string;
  
  // Global options
  overwrite: 'y' | 'n' | null;
  logLevel: 'quiet' | 'error' | 'warning' | 'info' | 'debug';
  stats: boolean;

  // Video Options
  videoCodec: string;
  videoBitrate: string;
  frameRate: string;
  aspectRatio: string;
  disableVideo: boolean;
  videoFilters: string;
  hardwareAccel: string; // e.g., 'auto', 'nvenc', 'qsv'

  // Audio Options
  audioCodec: string;
  audioBitrate: string;
  sampleRate: string;
  channels: string;
  disableAudio: boolean;
  audioFilters: string;

  // Subtitle
  disableSubtitle: boolean;
  subtitleCodec: string;

  // Timing
  startTime: string;
  duration: string;
  stopTime: string;

  // Advanced / AI
  customArgs: string;
  aiOverride: boolean; // If true, use the command generated by AI directly
  aiCommand: string;
  metadata: Record<string, string>;
  parallel: boolean;
  aiSource: 'gemini' | 'ollama';
  ollamaModel: string;
  ollamaServer: string;
}

export interface Preset {
  id: number;
  name: string;
  config_json: string;
  created_at: string;
}

export interface HistoryItem {
  id: number;
  command: string;
  status: 'success' | 'failed';
  stderr: string;
  timestamp: string;
}

export const INITIAL_STATE: FFmpegState = {
  language: 'zh-TW',
  mode: 'simple',
  inputFiles: ['input.mp4'],
  outputFile: 'output.mp4',
  format: '',
  overwrite: 'y',
  logLevel: 'info',
  stats: true,
  videoCodec: 'libx264',
  videoBitrate: '',
  frameRate: '',
  aspectRatio: '',
  disableVideo: false,
  videoFilters: '',
  hardwareAccel: 'auto',
  audioCodec: 'aac',
  audioBitrate: '',
  sampleRate: '',
  channels: '',
  disableAudio: false,
  audioFilters: '',
  disableSubtitle: false,
  subtitleCodec: '',
  startTime: '',
  duration: '',
  stopTime: '',
  customArgs: '',
  aiOverride: false,
  aiCommand: '',
  metadata: {},
  parallel: false,
  aiSource: 'gemini',
  ollamaModel: 'llama3.2:latest',
  ollamaServer: '/ollama',
};